version: 0.2
#run-as: ubuntu

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Entered the install phase on `date`...
      - python3 -m venv venv
  pre_build:
    commands:
      - echo Start pre_build on `date`...
      - . venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo Start Test on `date`
      - python manage.py test review.tests
