version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Entered the install phase on `date`...
      - python3 -m venv venv
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update -y
      - apt-get install -y mysql-server
      - service mysql start
  pre_build:
    commands:
      - echo Start pre_build on `date`...
      - . venv/bin/activate
      - pip install -r requirement/base.txt
      - pip install -r requirement/codeBuild.txt
      - python manage.py migrate

  build:
    commands:
      - echo Start Test on `date`
      - python manage.py test review.tests.test_models --settings config.settings.codeBuild
      - python manage.py test review.tests.test_urls --settings config.settings.codeBuild
      - python manage.py test review.tests.test_views --settings config.settings.codeBuild