# Generated by Django 3.2.9 on 2022-02-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_is_publishied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_publishied',
            new_name='is_published',
        ),
    ]
