# Generated by Django 3.2.9 on 2022-02-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rename_is_publishied_review_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_published',
        ),
    ]
