# Generated by Django 3.2.9 on 2022-03-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20220314_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=100, verbose_name='レビュー'),
        ),
        migrations.AlterField(
            model_name='review',
            name='storeName',
            field=models.CharField(max_length=30, verbose_name='店名'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=30, verbose_name='タイトル'),
        ),
    ]
