# Generated by Django 3.2.9 on 2022-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20220321_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='appendedPicture',
            field=models.ImageField(blank=True, null=True, upload_to='reviewPicture'),
        ),
    ]
